#!/usr/bin/env python3
"""Audit WAV assets used by AUDIO_EVENTS."""

import json
import wave
from pathlib import Path


AUDIO_DIR = Path("static/audio")
AUDIO_EVENTS = {
    "system_ready": "system_ready.wav",
    "scan_success": "scan_success.wav",
    "unknown_product": "unknown_product.wav",
    "scan_failed": "scan_failed.wav",
    "add_cart": "add_cart.wav",
    "payment_wait": "payment_wait.wav",
    "payment_success": "payment_success.wav",
    "capture_start": "capture_start.wav",
    "capture_success": "capture_success.wav",
    "capture_busy": "capture_busy.wav",
    "capture_failed": "capture_failed.wav",
    "remove_last": "remove_last.wav",
    "cart_clear": "cart_clear.wav",
    "total_query": "total_query.wav",
    "input_routed_scan": "input_routed_scan.wav",
    "voice_ready": "voice_ready.wav",
    "voice_processing": "voice_processing.wav",
    "voice_success": "voice_success.wav",
    "voice_failed": "voice_failed.wav",
}

PROMPT_TEXT = {
    "system_ready": "系统已启动",
    "scan_success": "商品已加入购物车",
    "unknown_product": "未录入商品，请重新扫码",
    "scan_failed": "扫码失败，请重试",
    "add_cart": "商品已加入购物车",
    "capture_start": "开始拍照",
    "capture_success": "拍照完成",
    "capture_busy": "摄像头忙，请稍后",
    "capture_failed": "拍照失败，请重试",
    "remove_last": "已删除上一件商品",
    "cart_clear": "购物车已清空",
    "total_query": "已查询总价，请查看屏幕",
    "payment_wait": "已生成订单，请扫码支付",
    "payment_success": "支付成功",
    "voice_ready": "请说话",
    "voice_processing": "正在识别",
    "voice_success": "识别成功",
    "voice_failed": "未识别，请重试",
    "input_routed_scan": "检测到条码，已转为扫码",
}

RECOMMENDED_WAV = {
    event: event + ".wav" for event in PROMPT_TEXT
}
RECOMMENDED_WAV.update({
    "scan_success": "scan_success.wav",
    "unknown_product": "unknown_product.wav",
    "scan_failed": "scan_failed.wav",
    "add_cart": "add_cart.wav",
    "capture_start": "capture_start.wav",
    "capture_success": "capture_success.wav",
    "capture_busy": "capture_busy.wav",
    "capture_failed": "capture_failed.wav",
    "remove_last": "remove_last.wav",
    "cart_clear": "cart_clear.wav",
    "total_query": "total_query.wav",
    "payment_wait": "payment_wait.wav",
    "payment_success": "payment_success.wav",
    "voice_ready": "voice_ready.wav",
    "voice_processing": "voice_processing.wav",
    "voice_success": "voice_success.wav",
    "voice_failed": "voice_failed.wav",
    "input_routed_scan": "input_routed_scan.wav",
})

SEMANTIC_DIRECT = {
    event: filename for event, filename in AUDIO_EVENTS.items()
}


def wav_info(path):
    if not path.exists():
        return {"exists": False}
    try:
        with wave.open(str(path), "rb") as w:
            frames = w.getnframes()
            rate = w.getframerate()
            return {
                "exists": True,
                "duration_sec": round(frames / float(rate or 1), 3),
                "sample_rate": rate,
                "channels": w.getnchannels(),
                "sample_width": w.getsampwidth(),
            }
    except Exception as exc:
        return {"exists": True, "error": str(exc)}


def main():
    rows = []
    for event, filename in sorted(AUDIO_EVENTS.items()):
        path = AUDIO_DIR / filename
        info = wav_info(path)
        direct = SEMANTIC_DIRECT.get(event) == filename
        recommended = RECOMMENDED_WAV.get(event, event + ".wav")
        reused = not direct or filename != recommended
        row = {
            "event": event,
            "wav": filename,
            "recommended_wav": recommended,
            "recommended_text": PROMPT_TEXT.get(event, ""),
            "path": str(path),
            "exists": bool(info.get("exists")),
            "duration_sec": info.get("duration_sec"),
            "sample_rate": info.get("sample_rate"),
            "channels": info.get("channels"),
            "human_voice": "unknown",
            "chinese_semantics_match": "yes" if direct else "unknown_reused",
            "reused_from": "" if not reused else filename,
            "recommend_replace": bool(reused),
            "acceptable_for_demo": bool(info.get("exists")),
            "note": "Need human listening audit before final release.",
        }
        rows.append(row)
    report = {
        "ok": all(r["exists"] for r in rows),
        "audio_dir": str(AUDIO_DIR),
        "events": rows,
        "honest_status": "WAV presence checked; true Chinese human voice semantics require listening/recording audit.",
    }
    out = Path("AUDIO_ASSET_AUDIT_REPORT.md")
    lines = ["# Audio Asset Audit Report", "", "Generated by `tools/audio_asset_audit.py`.", ""]
    lines.append("| Event | Current WAV | Recommended WAV | Text | Exists | Duration | Voice | Semantics | Replace |")
    lines.append("|---|---|---|---|---:|---:|---|---|---:|")
    for r in rows:
        lines.append("| {event} | {wav} | {recommended_wav} | {recommended_text} | {exists} | {duration_sec} | {human_voice} | {chinese_semantics_match} | {recommend_replace} |".format(**r))
    lines.extend(["", "```json", json.dumps(report, ensure_ascii=False, indent=2), "```", ""])
    out.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["ok"] else 2


if __name__ == "__main__":
    raise SystemExit(main())
